[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  port = 8888
  functionsPort = 9000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 